### ISSUE TITLE
Yoshimi Docs

### ISSUE THREAD

**Issue by abrolag** [ahlstromcj/yoshimi-doc#1]
Nice to see your work here.
To get up-to-date info on what is happening with Yoshimi you might like to join the list:
yoshimi-user@lists.sourceforge.net

**Comment by ahlstromcj** [comment]
Will do!

My main motivation for the document was figuring out how to properly use the
ring modulator (I had one of those modules back in my ancient PAIA days).

You are welcome to clone the project and start updating documents in
whatever way you want, it is fairly modular.  You can then issue pull
requests.  I'm still new to GitHub, so not totally sure how to handle them
outside the GitHub web interface.

Complaints and suggestions welcome as well.  It's only partly "my" document.

-------- Will J Godfrey 06:12 Sun 05 Jul      --------

> Nice to see your work here.
> To get up-to-date info on what is happening with Yoshimi you might like to join the list:
> yoshimi-user@lists.sourceforge.net
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ahlstromcj/yoshimi-doc/issues/1

## 

PIZZA!!

**Comment by abrolag** [comment]
On Sun, 05 Jul 2015 07:04:15 -0700
"C. Ahlstrom" notifications@github.com wrote:

> Will do!
> 
> My main motivation for the document was figuring out how to properly use the
> ring modulator (I had one of those modules back in my ancient PAIA days).

Heh. Often the way... then you get sucked in :)

> You are welcome to clone the project and start updating documents in
> whatever way you want, it is fairly modular.  You can then issue pull
> requests.  I'm still new to GitHub, so not totally sure how to handle them
> outside the GitHub web interface.

I'm actually up to my eyeballs in the code itself so don't really want to spend
much time 'elsewhere' but at the same time like to see that someone is putting
together a much-needed guide.

It's much easier for me to just fire off an email when someone asks "What does
Foo do, and why doesn't it Bar?" either by email or via the users list.

> Complaints and suggestions welcome as well.  It's only partly "my" document.

One thing that causes me some concern is that you wrote that Yoshimi crashed
when you tried to rename banks. Can you give me more details? I've never had
that happen, and as far as I know no one else has reported it.

A note on banks. You _really_ need to move some of those out to a new root!
That's a pretty crowded list. The limit is 128 and you seem to be half way
there :)

The numbers are generated the first time yoshimi sees a new root path or new
banks within a root path.

Once set, these numbers will never change unless you actually move them around
using the 'swap' button.

The number is also the MIDI ID so you can be sure it will always be there for
bank changes no matter how many more banks you add later.

Yoshimi always lists these in ID order not alphabetical order, so you can group
them sensibly and permanently. However, at first time creation it sets the
IDs in alphabetical order and tries to space them evenly over the range to give
you 'wiggle' room.

P.S.
Using right mouse click often produces modified or alternate results,
especially in roots/banks/instruments. In Yoshi this is defined as button
number 2. Some distros/window managers have number 2 as the middle button.

## 

Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Comment by ahlstromcj** [comment]
Will, thanks for the extra info.  I've been at the hospital for a hip
replacement (too much running and soccer), so it will take me a bit to get
back on track.

I will try to build and run yoshimi 1.3.5 and 1.3.5.1 under valgrind; that
usually pinpoints the problem quick.  How do I build yoshimi in Debug mode?
(I don't use cmake for my project.)

If I don't find the bugs, I'll at least get you the exact steps to set up
the bug.  There's a less one with instruments that just causes a "normal"
exit.

Thanks!

Chris

-------- Will J Godfrey 14:37 Mon 06 Jul      --------

> On Sun, 05 Jul 2015 07:04:15 -0700
> "C. Ahlstrom" notifications@github.com wrote:
> 
> > Will do!
> > 
> > My main motivation for the document was figuring out how to properly use the
> > ring modulator (I had one of those modules back in my ancient PAIA days).
> 
> Heh. Often the way... then you get sucked in :)
> 
> > You are welcome to clone the project and start updating documents in
> > whatever way you want, it is fairly modular.  You can then issue pull
> > requests.  I'm still new to GitHub, so not totally sure how to handle them
> > outside the GitHub web interface.
> 
> I'm actually up to my eyeballs in the code itself so don't really want to spend
> much time 'elsewhere' but at the same time like to see that someone is putting
> together a much-needed guide.
> 
> It's much easier for me to just fire off an email when someone asks "What does
> Foo do, and why doesn't it Bar?" either by email or via the users list.
> 
> > Complaints and suggestions welcome as well.  It's only partly "my" document.
> 
> One thing that causes me some concern is that you wrote that Yoshimi crashed
> when you tried to rename banks. Can you give me more details? I've never had
> that happen, and as far as I know no one else has reported it.
> 
> A note on banks. You _really_ need to move some of those out to a new root!
> That's a pretty crowded list. The limit is 128 and you seem to be half way
> there :)
> 
> The numbers are generated the first time yoshimi sees a new root path or new
> banks within a root path.
> 
> Once set, these numbers will never change unless you actually move them around
> using the 'swap' button.
> 
> The number is also the MIDI ID so you can be sure it will always be there for
> bank changes no matter how many more banks you add later.
> 
> Yoshimi always lists these in ID order not alphabetical order, so you can group
> them sensibly and permanently. However, at first time creation it sets the
> IDs in alphabetical order and tries to space them evenly over the range to give
> you 'wiggle' room.
> 
> P.S.
> Using right mouse click often produces modified or alternate results,
> especially in roots/banks/instruments. In Yoshi this is defined as button
> number 2. Some distros/window managers have number 2 as the middle button.
> 
> ## 
> 
> Will J Godfrey
> http://www.musically.me.uk
> Say you have a poem and I have a tune.
> Exchange them and we can both have a poem, a tune, and a song.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ahlstromcj/yoshimi-doc/issues/1#issuecomment-119004809

## 

Are you still an ALCOHOLIC?

**Comment by abrolag** [comment]
On Wed, 08 Jul 2015 17:05:58 -0700
"C. Ahlstrom" notifications@github.com wrote:

> Will, thanks for the extra info.  I've been at the hospital for a hip
> replacement (too much running and soccer), so it will take me a bit to get
> back on track.

Understand - these things take a long time to sort themselves out.

> I will try to build and run yoshimi 1.3.5 and 1.3.5.1 under valgrind; that
> usually pinpoints the problem quick.  How do I build yoshimi in Debug mode?
> (I don't use cmake for my project.)

Hmm. That may have something to do with it. Right back to Zyn V2.2.1 this has
always been a cmake build. All the build options are listed and set using
ccmake . Quite honestly I don't know any other way to set it up for a make!

What architecture are you building on? I've tested both intel and amd, 32 & 64
bit. The debian guys have also built for arm and mips and haven't reported any
problems.

## 

Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.
